// namespace CommonDomain.Core.Generators.Attributes;
//
// [Generator]
// public class ValueObjectAttributeGenerator : IIncrementalGenerator
// {
//     private const string Namespace = "Generators.Attributes";
//
//     private const string AttributeName = "ValueObjectAttribute";
//     
//     private const string SourceCode = $@"// <auto-generated/>
// namespace {Namespace};
//
// [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
// public sealed partial class {AttributeName} : System.Attribute;";
//
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         // Add the marker attribute to the compilation.
//         context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
//             $"{AttributeName}.g.cs",
//             SourceText.From(SourceCode, Encoding.UTF8)));
//     }
// }