using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CommonDomain.Generators.InterfaceGenerators;

[Generator]
public class DomainEventSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "Generators.Interfaces";

    private const string Name = "IDomainEvent";
    
    private const string SourceCode = $@"// <auto-generated/>
namespace {Namespace};

public interface IDomainEvent {{ /* Marker interface, might have Timestamp etc. */ }}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"{Name}.g.cs",
            SourceText.From(SourceCode, Encoding.UTF8)));
    }
}