using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CommonDomain.Generators.InterfaceGenerators;

[Generator]
public class ValueObjectSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "Generators.Common";

    private const string Name = "IValueObject";
    
    private const string SourceCode = $@"// <auto-generated/>
namespace {Namespace};

public interface IValueObject;";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"{Name}.g.cs",
            SourceText.From(SourceCode, Encoding.UTF8)));
    }
}