namespace CommonDomain.Generators.Generators.Interfaces;

[Generator]
public class DateTimeProviderGenerator : IIncrementalGenerator
{
    private const string Namespace = "Generators.Interfaces";

    private const string Name = "IDateTimeProvider";
    
    private const string SourceCode = $@"// <auto-generated/>
using System;

namespace {Namespace};

public partial interface IDateTimeProvider
{{
    DateTime UtcNow {{ get; }}
}}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"{Name}.g.cs",
            SourceText.From(SourceCode, Encoding.UTF8)));
    }
}