namespace CommonDomain.Generators.Generators.Interfaces;

[Generator]
public class DomainEventGenerator : IIncrementalGenerator
{
    private const string Namespace = "Generators.Interfaces";

    private const string Name = "IDomainEvent";
    
    private const string SourceCode = $@"// <auto-generated/>
namespace {Namespace};

public partial interface IDomainEvent {{ /* Marker interface, might have Timestamp etc. */ }}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"{Name}.g.cs",
            SourceText.From(SourceCode, Encoding.UTF8)));
    }
}