namespace CommonDomain.Core.Generators.AggregateRoots;

[Generator]
public class AggregateRootGenerator : IIncrementalGenerator
{
    private const string Namespace = $"{Constance.NamespaceBase}.AggregateRoots";
    
    private const string SourceCode = $@"// <auto-generated/>
#nullable enable
using System.Collections.Generic;
using {Constance.NamespaceBase}.Entities;
using {Constance.NamespaceBase}.Ids;
using {Constance.NamespaceBase}.Interfaces;

namespace {Namespace};

public abstract partial class AggregateRoot<TId> : Entity<TId> where TId : IEntityId<TId>
{{
    private readonly List<IDomainEvent> _domainEvents = new();
    public IReadOnlyCollection<IDomainEvent> DomainEvents => _domainEvents.AsReadOnly();
    protected void AddDomainEvent(IDomainEvent domainEvent)
    {{
        ArgumentNullException.ThrowIfNull(domainEvent);
        _domainEvents.Add(domainEvent);
    }}
    
    public void ClearDomainEvents() => _domainEvents.Clear();
    
    protected AggregateRoot(TId id) : base(id)
    {{
    }}

    protected AggregateRoot() : base(TId.CreateUniqueId()) {{ }}
}}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"AggregateRoot.g.cs",
            SourceText.From(SourceCode, Encoding.UTF8)));
    }
}