namespace CommonDomain.Generators.Entities;

public static class PropertyUpdaterCode
{
    public static string UpdaterWithValidation(string validationBody, string propertyName, string propertyType)
    {
        var code = $@"// <auto-generated/>
    public Result<Updated, Error> Update{propertyName}({propertyType} new{propertyName})
    {{
        {validationBody}
        {propertyName} = new{propertyName};
        return Result.Updated;
    }}";
        
        return code;
    }
    public static string UpdaterSimple(string propertyName, string propertyType)
    {
        var code = $@"// <auto-generated/>
    public Updated Update{propertyName}({propertyType} new{propertyName})
    {{
        {propertyName} = new{propertyName};
        return Result.Updated;
    }}";
        
        return code;
    }
}