using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CommonDomain.Generators.AttributeGenerator;

[Generator]
public class WithEntityIdSourceAttributeGenerator : IIncrementalGenerator
{
    private const string Namespace = "Generators.Attributes";

    private const string AttributeName = "EntityAttribute";
    
    private const string SourceCode = $@"// <auto-generated/>
namespace {Namespace};

[System.AttributeUsage(System.AttributeTargets.Class)]
public sealed partial class {AttributeName} : System.Attribute;";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"{AttributeName}.g.cs",
            SourceText.From(SourceCode, Encoding.UTF8)));
    }
}